name: Automated Preprocessing

on:
  push:
    branches: [ main ]
    paths:
      - 'Eksperimen_SML_yim/dataset/cs-training.csv'
      - 'Eksperimen_SML_yim/dataset/cs-test.csv'
      - 'Eksperimen_SML_yim/preprocessing/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Eksperimen_SML_yim/dataset/cs-training.csv'
      - 'Eksperimen_SML_yim/dataset/cs-test.csv'
      - 'Eksperimen_SML_yim/preprocessing/**'
  workflow_dispatch:

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_yim.py

      - name: Move processed data
        run: |
          mv train_pca.csv preprocessing/
          mv test_pca.csv preprocessing/

      - name: Commit processed data
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add preprocessing/train_pca.csv preprocessing/test_pca.csv
          git commit -m 'Berhasil update dataset' || echo "No changes to commit"
          git push
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}